AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create a DynamoDB table with TTL enabled.

Resources:
  MyDynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Product
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
        - AttributeName: product_name
          AttributeType: S
        - AttributeName: price
          AttributeType: N
        - AttributeName: ttl_live
          AttributeType: N
      KeySchema: 
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TimeToLiveSpecification:
        AttributeName: ttl_live
        Enabled: true
